-- ============================================================
-- La Voglia — seed dati iniziali. Esegui DOPO schema.sql.
-- Generato da src/data/menu.json.
-- ============================================================

truncate public.tap_beers, public.panini, public.focacce, public.bottle_beers, public.gins;

insert into public.tap_beers (sort_order, short_name, name, origin, style_abv, flag, description, price_small, price_medium, price_liter, disc_bg, disc_border, disc_ring, disc_text, disc_sub, is_special) values
  (1, 'Pilsner Urquell', 'Pilsner Urquell', '🇨🇿 Repubblica Ceca · Pilsner', 'Pilsner · 4.4%', '🇨🇿', 'La Pilsner originale dal 1842. Amara, dorata, cristallina. L''archetipo di uno stile mondiale.', '€3,50', '€5,50', '€11', 'linear-gradient(135deg,#f8f8f0 0%,#e8e8d8 100%)', '#1B5E20', 'rgba(27,94,32,.4)', '#C8102E', '#1B5E20', false),
  (2, 'London Pride', 'Fuller''s London Pride', '🏴󠁧󠁢󠁥󠁮󠁧󠁿 Inghilterra · English Bitter', 'Bitter · 4.7%', '🏴󠁧󠁢󠁥󠁮󠁧󠁿', 'L''iconico bitter di Fuller''s. Rame brillante, sentori di malto tostato e frutta. Classico britannico.', '€3,70', '€6,00', '€12', 'radial-gradient(circle,#8B1A1A 0%,#560000 100%)', '#C8A000', 'rgba(200,160,0,.35)', null, null, false),
  (3, 'Kozel Dark', 'Velkopopovický Kozel Dark', '🇨🇿 Repubblica Ceca · Dark Lager', 'Lager Scura · 3.5%', '🇨🇿', 'Vellutata, caramellata, sorprendentemente morbida e leggera. La dark lager ceca per eccellenza.', '€3,70', '€6,00', '€12', 'radial-gradient(circle,#6D3B1A 0%,#3D1F08 100%)', '#D4A017', 'rgba(212,160,23,.3)', null, null, false),
  (4, 'Grolsch Weizen', 'Grolsch Weizen', '🇳🇱 Olanda · Weizen', 'Frumento · 5.3%', '🇳🇱', 'Freschezza agrumata, note di banana e spezie. Soffice e cremosa, perfetta abbinata a panini leggeri.', '€3,70', '€6,00', '€12', 'radial-gradient(circle,#2E7D32 0%,#0D4A10 100%)', '#FFD700', 'rgba(255,215,0,.3)', null, null, false),
  (5, 'Andechs', 'Kloster Andechs Doppelbock Dunkel', '🇩🇪 Baviera · Doppelbock', 'Doppelbock · 7%', '🇩🇪', 'Monastica e intensa. Cioccolato fondente, pane tostato, struttura corposa. La birra del monastero bavarese.', '€3,70', '€6,00', '€12', 'radial-gradient(circle,#1A237E 0%,#080E50 100%)', '#FFFFFF', 'rgba(255,255,255,.2)', null, null, false),
  (6, 'Delirium Tremens', 'Delirium Tremens', '🇧🇪 Belgio · Strong Golden Ale', 'Strong Blond · 8.5%', '🇧🇪', 'L''iconica bottiglia rosa con gli elefanti. Complessa, speziata, leggendaria. Una delle migliori belghe al mondo.', '€3,70', '€6,00', '€12', 'radial-gradient(circle,#1565C0 0%,#003898 100%)', '#FFB3C6', 'rgba(255,179,198,.3)', null, null, false),
  (7, 'Uiltje IPA', 'Uiltje Brewing Co.', '🇳🇱 Olanda · Haarlem · IPA', 'IPA · 7.2%', '🇳🇱', 'Craft brewery di Haarlem con il gufo come simbolo. IPA luppolata, tropicale e resinosa — il carattere olandese moderno.', '€3,70', '€6,00', '€12', 'linear-gradient(135deg,#FFD400 0%,#E5B800 100%)', '#111111', 'rgba(0,0,0,.35)', '#111111', '#333333', false),
  (8, 'Birra del Mese', 'Birra del Mese', '🌍 A rotazione mensile', 'A rotazione', '🔄', 'Ogni mese una novità da scoprire — una birra speciale che arriva direttamente da noi al tuo bicchiere. Chiedi quale è disponibile!', '€3,70', '€6,00', '€12', 'radial-gradient(circle,#5D4037 0%,#2C1B0E 100%)', '#dcb356', 'rgba(220,179,86,.3)', null, null, true);

insert into public.panini (number, name, price) values
  (1, 'Prosciutto cotto, uovo tonno, insalata, mozzarella, maionese o tonnè', '4,80€'),
  (2, 'Prosciutto crudo', '3,90€'),
  (3, 'Prosciutto crudo, brié', '4,50€'),
  (4, 'Fontal, formaggio tipo caprino, brié, crema di formaggi', '4,40€'),
  (5, 'Fesa di tacchino arrosto, tonnè', '4,30€'),
  (6, 'Fesa di tacchino arrosto, pomodoro, insalata', '4,50€'),
  (7, 'Pomodoro, uovo, tonno, maionese, insalata', '4,50€'),
  (8, 'Wurstel, senape', '4,00€'),
  (9, 'Prosciutto cotto, capricciosa', '4,10€'),
  (10, 'Salame Milano, formaggio tipo caprino', '4,50€'),
  (11, 'Coppa, brié', '4,60€'),
  (12, 'Pomodoro, verdure grigliate, insalata, maionese', '4,20€'),
  (13, 'Peperoni, acciughe, cipolle', '4,00€'),
  (14, 'Gamberetti in salsa al rum, insalata', '6,00€'),
  (15, 'Pomodori secchi, crema ai funghi porcini, fontal, insalata', '4,20€'),
  (16, 'Hamburger alla diavola — senape, ketchup, cipolle, peperoncino', '5,20€'),
  (17, 'Hamburger, fontal, ketchup', '4,80€'),
  (18, 'Pomodoro, mozzarella, acciughe, origano', '4,50€'),
  (19, 'Speck, formaggio tipo caprino', '4,50€'),
  (20, 'Wurstel alla diavola — senape, ketchup, cipolle, peperoncino', '4,50€'),
  (21, 'Bresaola, pepe, sale, olio, limone', '5,00€'),
  (22, 'Gamberetti, insalata, olio, pepe, limone', '5,80€'),
  (23, 'Coppa', '4,10€'),
  (24, 'Salame Milano', '4,00€'),
  (25, 'Prosciutto cotto', '3,80€'),
  (26, 'Prosciutto cotto, fontal', '4,20€'),
  (27, 'Wurstel, crauti, senape', '4,50€'),
  (28, 'Milanese di pollo, pomodoro, maionese, sale, pepe', '5,20€'),
  (29, 'Milanese di pollo, pepe, sale, limone, insalata', '5,20€'),
  (30, 'Bagnetto, peperoni, acciughe', '4,00€'),
  (31, 'Prosciutto crudo, gamberetti in salsa al rum', '6,50€'),
  (32, 'Salame ungherese, scamorza affumicata', '4,70€'),
  (33, 'Prosciutto cotto, melanzane grigliate, fontal', '4,50€'),
  (34, 'Pomodoro, mozzarella, fontal, melanzane grigliate', '4,50€'),
  (35, 'Speck, cipolla, patè di olive, insalata', '4,90€'),
  (36, 'Speck, formaggio tipo caprino, spinaci', '4,80€'),
  (37, 'Salame Milano, asparagi, maionese', '4,60€'),
  (38, 'Hamburger, salsa al rum, salsa di asparagi, fontal', '5,20€'),
  (39, 'Bresaola, fontal, maionese', '5,60€'),
  (40, 'Pomodoro, mozzarella, olio, sale, origano', '4,00€'),
  (41, 'Hamburger, spinaci, fontal, senape', '5,20€'),
  (42, 'Hamburger, pomodoro, insalata', '4,80€'),
  (43, 'Prosciutto cotto, peperoni, formaggio tipo caprino', '4,70€'),
  (44, 'Prosciutto cotto, fontal, spinaci, maionese, pepe', '4,90€'),
  (45, 'Prosciutto crudo, pomodoro', '4,50€'),
  (46, 'Spinaci, formaggio tipo caprino', '3,80€'),
  (47, 'Fesa di tacchino arrosto, uovo, maionese', '4,60€'),
  (48, 'Wurstel, fontal', '4,20€'),
  (49, 'Prosciutto cotto, salsa di asparagi, mozzarella', '4,60€'),
  (50, 'Salame ungherese, peperoni, fontal', '4,90€'),
  (51, 'Wurstel, capricciosa, insalata', '4,50€'),
  (52, 'Prosciutto crudo, capricciosa', '4,50€'),
  (53, 'Coppa, vodka, limone, olio, pepe, sale', '4,50€'),
  (54, 'Bresaola, vodka, limone, salsa di asparagi, mozzarella, salsa al rum', '5,90€'),
  (55, 'Frittata di spinaci, pomodoro, insalata, mozzarella', '5,10€'),
  (56, 'Prosciutto cotto, frittata di spinaci, mozzarella, maionese', '6,00€'),
  (57, 'Frittata di spinaci, cipolle, fontal, sale, pepe', '5,10€'),
  (58, 'Frittata di spinaci, salsa di carciofi, pomodoro, insalata', '5,10€'),
  (59, 'Bresaola, salsa di carciofi, crema di formaggi', '5,60€'),
  (60, 'Pomodori secchi, cipolle, patè di olive nere, insalata, tonnè, maionese', '4,10€'),
  (61, 'Prosciutto cotto, pomodori secchi, crema di formaggi, insalata', '5,00€'),
  (62, 'Pomodori secchi, acciughe, patè di olive nere, crema di formaggi, insalata', '4,70€'),
  (63, 'Crema di formaggi, tonno, uovo, salsa di carciofi', '3,90€'),
  (64, 'Crema di formaggi, salsa di carciofi', '3,60€'),
  (65, 'Prosciutto cotto, crema ai formaggi, crema ai funghi porcini, insalata', '5,00€'),
  (66, 'Crema di formaggi, gamberetti, pepe', '6,00€'),
  (67, 'Nutella, o burro d''arachidi o marmellata', '3,50€'),
  (68, 'Fesa di tacchino arrosto, crema ai funghi al tartufo, crema di formaggi', '5,50€'),
  (69, 'Wurstel, patatine, maionese', '4,50€'),
  (70, 'Hamburger, pesto di pistacchi, crudo croccante, crema ai formaggi', '6,80€'),
  (71, 'Wurstel, cipolle, salsa di fuoco, fontal', '5,00€'),
  (72, 'Hamburger, salsa di fuoco, scamorza affumicata', '5,30€'),
  (73, 'Formaggio tipo caprino, zucchine grigliate', '3,90€'),
  (74, 'Coppa, crema di noci, pomodori secchi', '5,20€'),
  (75, 'Fesa di tacchino arrosto, pomodoro, zucchine grigliate, mozzarella', '5,50€'),
  (76, 'Bresaola, pesto di pistacchi, crema di formaggi', '5,70€'),
  (77, 'Gamberetti, crema di funghi al tartufo, maionese', '6,30€'),
  (78, 'Speck, salsa alle noci, brié', '5,50€'),
  (79, 'Speck, zucchine grigliate, brié', '5,50€'),
  (80, 'Pesto di pistacchi, formaggio tipo caprino, melanzane grigliate, pomodoro', '5,20€'),
  (81, 'Speck, pomodori secchi, crema di funghi al tartufo', '5,70€'),
  (82, 'Fesa di tacchino arrosto, maionese, crema di funghi porcini, pomodoro, brié', '5,50€'),
  (83, 'Pomodoro, salsa alle noci, insalata, pesto di pistacchi', '4,00€'),
  (84, 'Hamburger, pomodoro, insalata, crema di formaggi, scamorza affumicata', '5,20€'),
  (85, 'Melanzane, verdure miste, fontal, maionese, insalata', '4,60€'),
  (86, 'Prosciutto cotto, burro di arachidi, pomodoro, sale, pepe, insalata', '4,80€'),
  (87, 'Hamburger, formaggio tipo caprino, verdure grigliate, maionese, crudo croccante', '6,90€'),
  (88, 'Doppio hamburger, maionese, pomodoro, ketchup, fontal, insalata', '7,50€'),
  (89, 'Hamburger, salsa alle noci, scamorza affumicata, speck croccante', '6,80€'),
  (90, 'Salame croccante, formaggio pecorino, zucchine, salsa di fuoco', '5,20€'),
  (91, 'Hamburger, formaggio pecorino, patè di olive nere, pomodoro, insalata', '5,30€'),
  (92, 'Fesa di tacchino arrosto, burro di arachidi, verdure miste, formaggio pecorino', '5,50€'),
  (93, 'Fesa di tacchino arrosto, maionese, cipolle, pomodoro, pepe, uovo, senape, fontal, crudo croccante, insalata', '6,90€'),
  (94, 'Prosciutto cotto, pesto al sesamo, spinaci', '5,00€'),
  (95, 'Salame Milano, bagnetto, acciughe', '5,00€'),
  (96, 'Gamberetti, formaggio pecorino, pomodoro, pepe, pesto al sesamo', '6,60€'),
  (97, 'Frittata di spinaci, crema di funghi al tartufo, maionese, fontal, pepe', '5,60€'),
  (98, 'Coppa, formaggio pecorino, zucchine grigliate, fontal, pesto al sesamo', '5,60€'),
  (99, 'Pesto al sesamo, pomodori secchi, acciughe, maionese, origano', '4,80€'),
  (100, 'Salame Milano, formaggio pecorino, pesto al sesamo, pomodori secchi, insalata', '4,90€');

insert into public.focacce (sort_order, label, name, sub, price) values
  (1, 'TOAST', 'Prosciutto cotto, fontal', 'Pane bianco, integrale o 5 cereali', '2,80€'),
  (2, 'TOAST FARCITO', 'Prosciutto cotto, fontal, verdure miste o peperoni o salsa di carciofi o crema ai funghi al tartufo', null, '3,00€'),
  (3, 'TOAST', 'Nutella', null, '1,50€'),
  (4, 'FOCACCIA 1', 'Prosciutto cotto, pomodoro, mozzarella, maionese', null, '4,60€'),
  (5, 'FOCACCIA 2', 'Prosciutto crudo', null, '4,30€'),
  (6, 'FOCACCIA FELICE', 'Sale, olio, origano o rosmarino', null, '1,50€'),
  (7, 'FOCACCIA RAFFO', 'Prosciutto cotto, cotoletta di pollo, pomodoro, mozzarella, maionese', null, '6,10€'),
  (8, 'PIZZETTA', 'Piccola', null, '2,00€'),
  (9, 'PIZZETTA', 'Piccola al prosciutto o ai peperoni', null, '2,50€'),
  (10, 'PIZZETTA', 'Grande', null, '4,00€'),
  (11, 'PIZZETTA', 'Grande al prosciutto o ai peperoni', null, '4,90€'),
  (12, 'BRETZEL', '🥨 Bretzel', null, '1,50€');

insert into public.bottle_beers (sort_order, badge, name, sub, price, badge_bg, badge_color) values
  (1, 'FW', 'Firestone Walker', 'USA · California · 0,355l', '6,00€', 'linear-gradient(135deg,#5D4037,#3E2723)', '#FFCCBC'),
  (2, 'KS', 'Kloster Scheyern Weiss / Dunkel', 'Germania · 0,50l', '5,50€', 'linear-gradient(135deg,#4E342E,#2C1A0E)', '#D7CCC8'),
  (3, 'RB', 'Radeberger Pilsner', 'Germania · 0,50l', '5,50€', 'linear-gradient(135deg,#2E7D32,#1B5E20)', '#ffffff'),
  (4, 'SI', 'St. Idesbald Tripel', 'Belgio · 0,33l', '6,00€', 'linear-gradient(135deg,#8D6E63,#6D4C41)', '#BCAAA4'),
  (5, 'RF', 'Raffo Grezza', 'Italia · 0,33l', '3,70€', 'linear-gradient(135deg,#D32F2F,#B71C1C)', '#ffffff'),
  (6, 'IC', 'Ichnusa Non Filtrata', 'Italia · Sardegna · 0,33l', '3,70€', 'linear-gradient(135deg,#1565C0,#003380)', '#E3F2FD'),
  (7, 'MS', 'Messina Cristalli di Sale', 'Italia · Sicilia · 0,33l', '3,70€', 'linear-gradient(135deg,#0D47A1,#1A237E)', '#FFD700'),
  (8, 'LF', 'Leffe Rouge', 'Belgio · 0,33l', '4,00€', 'linear-gradient(135deg,#C8840A,#8B5700)', '#FFF9C4'),
  (9, 'HNK', 'Heineken', 'Olanda · 0,33l', '4,00€', 'linear-gradient(135deg,#00843D,#005229)', '#ffffff'),
  (10, 'MT', 'Moretti', 'Italia · 0,66l', '4,00€', 'linear-gradient(135deg,#C62828,#8E0000)', '#FFD54F'),
  (11, 'DP', 'Desperados', 'Messico · Tequila Flavoured · 0,33l', '4,00€', 'linear-gradient(135deg,#00695C,#004D40)', '#A5D6A7'),
  (12, 'DAURA', 'Daura — Gluten Free 🌾', 'Spagna · Damm · 0,33l', '4,00€', 'linear-gradient(135deg,#A1720A,#785100)', '#E3F2FD');

insert into public.gins (sort_order, name, price) values
  (1, 'G''Vine Floraison', '9,00€'),
  (2, 'G''Vine Nouaison', '9,00€'),
  (3, 'Bombay Sapphire', '9,00€'),
  (4, 'Malfy Gin', '9,00€'),
  (5, 'Tanqueray London Dry', '9,00€'),
  (6, 'Mazzetti London Dry', '9,00€'),
  (7, 'Hendrick''s', '9,00€'),
  (8, 'Gin Mare', '9,00€'),
  (9, 'Bulldog', '9,00€'),
  (10, 'Monkey 47', '10,00€');

